#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$SCRIPT_DIR/..";
DB_PATH="$REPO_ROOT/test.db";

if [ -f $DB_PATH ]; then
  echo "Found db as $DB_PATH, doing nothing and exiting"
  exit 1
fi

if ! command -v sqlite3 &> /dev/null; then
  echo "Command \`sqlite3\` could not be found"
  exit 1
fi

touch $DB_PATH
sqlite3 $DB_PATH < $REPO_ROOT/src/database/migrations/merchant/*_setup.sql
sqlite3 $DB_PATH < $REPO_ROOT/src/database/migrations/customer/*_setup.sql
