name: E2E tests

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-docker-${{ github.sha }}
            ${{ runner.os }}-buildx-docker-
            ${{ runner.os }}-

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Tags
        id: tags
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="zeekoe_base"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}
      
      - name: Create custom Docker network
        run: docker network create e2e-net

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          driver-opts: network=e2e-net

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.tags.outputs.tagged_image }}

      - name: Run sandbox 
        run: |
           docker run --rm --name sandbox --network e2e-net --detach -p 20000:20000 tqtezos/flextesa:20210602 flobox start
           echo "SANDBOX_IP=docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sandbox" >> $GITHUB_ENV
          
      - name: Check
        run: echo "Sandbox IP:" ${{ env.SANDBOX_IP}}

      - name: Run tests (configure tezos client, run integration tests)
        uses: docker/build-push-action@v2
        with:
          file: ./integration_tests/Dockerfile
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          pull: true
          load: true
          build-args: |
            zeekoe_base=ghcr.io/${{ github.repository_owner }}/${{ steps.tags.outputs.tagged_image }}
            tezos_uri=${{ env.SANDBOX_IP }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
