name: E2E tests

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: $-buildx-docker-$
          restore-keys: |
            $-buildx-docker-
            $-buildx-

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: e2e tests
        id: e2e
        uses: ./.github/actions/e2e-action
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
