name: E2E tests

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "zeekoe"
          submodules: recursive

      - name: e2e tests
        id: e2e
        uses: ./.github/actions/e2e-action
